	ALTER TABLE [dbo].[StateMaster]
	ADD CONSTRAINT [PinIDFK]
	FOREIGN KEY (Pin)
	REFERENCES [PINMaster] (PINID)

	GO
	ALTER TABLE [dbo].[StateMaster]
	ADD CONSTRAINT [CityIDFK]
	FOREIGN KEY (City)
	REFERENCES [CityMaster](CityID)
